version: '3.8'

services:
  api:
    image: graphml/analysis
    build:
      context: ../
      dockerfile: GraphML.Analysis.Server/Dockerfile
    ports:
      - "6379:6379"
      - "61616:61616"
      - "8161:8161"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
